const fs = require('fs');
const path = 'E:/ALL PROJECT PORTAL/trimuryacorporation/frontend/src/pages/JobDetail.jsx';
const c = fs.readFileSync(path, 'utf8');
const imports = (c.match(/import\s+.*\s+from\s+['"].*?['"];?/g) || []).length;
const opens = (c.match(/<[A-Za-z][A-Za-z0-9]*\b/g) || []).length;
const closes = (c.match(/<\/[A-Za-z][A-Za-z0-9]*\s*>/g) || []).length;
const braces = (c.match(/{/g) || []).length;
const bracesClose = (c.match(/}/g) || []).length;
const parens = (c.match(/\(/g) || []).length;
const parensClose = (c.match(/\)/g) || []).length;
const brackets = (c.match(/\[/g) || []).length;
const bracketsClose = (c.match(/\]/g) || []).length;
console.log('Imports:', imports);
console.log('Open tags:', opens);
console.log('Close tags:', closes);
console.log('Open braces:', braces, 'Close braces:', bracesClose);
console.log('Open parens:', parens, 'Close parens:', parensClose);
console.log('Open brackets:', brackets, 'Close brackets:', bracketsClose);
console.log('Brace diff:', braces - bracesClose);
console.log('Paren diff:', parens - parensClose);
console.log('Bracket diff:', brackets - bracketsClose);
